# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (12)
# #########################################################################

class AdmissionDomesticQuestion(BaseModel):
    AdmissionDomestic_Subgroup: typing.Optional[types.AdmissionDomesticSubgroup] = None

class AdmissionInternationalQuestion(BaseModel):
    AdmissionInternational_Subgroup: typing.Optional[types.AdmissionInternationalSubgroup] = None

class ApplicationQuestion(BaseModel):
    Application_Subgroup: typing.Optional[types.ApplicationSubgroup] = None

class CareerQuestion(BaseModel):
    Career_Subgroup: typing.Optional[types.CareerSubgroup] = None

class ClassifiedQuestion(BaseModel):
    category: typing.Optional[typing.Union["RankingQuestion", "FinancialQuestion", "LocationQuestion", "CareerQuestion", "ApplicationQuestion", "AdmissionDomesticQuestion", "AdmissionInternationalQuestion", "ContactQuestion", "OtherQuestion"]] = None

class ContactQuestion(BaseModel):
    Contact_Subgroup: typing.Optional[types.ContactSubgroup] = None

class FinancialQuestion(BaseModel):
    Financial_Subgroup: typing.Optional[types.FinancialSubgroup] = None

class LocationQuestion(BaseModel):
    Location_Subgroup: typing.Optional[types.LocationSubgroup] = None

class OtherQuestion(BaseModel):
    UnAnswerable: typing.Optional[str] = None

class RankingQuestion(BaseModel):
    Ranking_Subgroup: typing.Optional[typing.Union[typing_extensions.Literal['Overall'], typing_extensions.Literal['CS'], typing_extensions.Literal['HealthScience'], typing_extensions.Literal['Math'], typing_extensions.Literal['Engineering'], typing_extensions.Literal['Business']]] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class UniQuery(BaseModel):
    group: typing.Optional[typing.Union[typing_extensions.Literal['Admission Requirements Domestic'], typing_extensions.Literal['Application Questions']]] = None
    subgroup: typing.Optional[typing.Union[typing_extensions.Literal['GPA'], typing_extensions.Literal['Dates']]] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
