# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (7)
# #########################################################################

class AdmissionDomesticSubgroup(str, Enum):
    GPA = "GPA"
    SAT = "SAT"
    ACT = "ACT"

class AdmissionInternationalSubgroup(str, Enum):
    GPA = "GPA"
    SAT = "SAT"
    ACT = "ACT"
    LANGUAGE = "LANGUAGE"

class ApplicationSubgroup(str, Enum):
    DATES = "DATES"
    FEES = "FEES"
    ED = "ED"
    EA = "EA"

class CareerSubgroup(str, Enum):
    COOP_INTERNSHIPS = "COOP_INTERNSHIPS"
    OUTCOMES = "OUTCOMES"
    LONG_TERM = "LONG_TERM"

class ContactSubgroup(str, Enum):
    ADMISSIONS = "ADMISSIONS"
    HEALTH_COUNSELING = "HEALTH_COUNSELING"
    DISABILITY = "DISABILITY"

class FinancialSubgroup(str, Enum):
    HOUSING = "HOUSING"
    TUITION = "TUITION"
    OTHER = "OTHER"

class LocationSubgroup(str, Enum):
    BOSTON = "BOSTON"
    OAKLAND = "OAKLAND"
    NEW_YORK = "NEW_YORK"

# #########################################################################
# Generated classes (12)
# #########################################################################

class AdmissionDomesticQuestion(BaseModel):
    AdmissionDomestic_Subgroup: AdmissionDomesticSubgroup

class AdmissionInternationalQuestion(BaseModel):
    AdmissionInternational_Subgroup: AdmissionInternationalSubgroup

class ApplicationQuestion(BaseModel):
    Application_Subgroup: ApplicationSubgroup

class CareerQuestion(BaseModel):
    Career_Subgroup: CareerSubgroup

class ClassifiedQuestion(BaseModel):
    category: typing.Union["RankingQuestion", "FinancialQuestion", "LocationQuestion", "CareerQuestion", "ApplicationQuestion", "AdmissionDomesticQuestion", "AdmissionInternationalQuestion", "ContactQuestion", "OtherQuestion"]

class ContactQuestion(BaseModel):
    Contact_Subgroup: ContactSubgroup

class FinancialQuestion(BaseModel):
    Financial_Subgroup: FinancialSubgroup

class LocationQuestion(BaseModel):
    Location_Subgroup: LocationSubgroup

class OtherQuestion(BaseModel):
    UnAnswerable: str

class RankingQuestion(BaseModel):
    Ranking_Subgroup: typing.Union[typing_extensions.Literal['Overall'], typing_extensions.Literal['CS'], typing_extensions.Literal['HealthScience'], typing_extensions.Literal['Math'], typing_extensions.Literal['Engineering'], typing_extensions.Literal['Business']]

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class UniQuery(BaseModel):
    group: typing.Union[typing_extensions.Literal['Admission Requirements Domestic'], typing_extensions.Literal['Application Questions']]
    subgroup: typing.Union[typing_extensions.Literal['GPA'], typing_extensions.Literal['Dates']]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
