# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AdmissionDomesticQuestion": types.AdmissionDomesticQuestion,
    "stream_types.AdmissionDomesticQuestion": stream_types.AdmissionDomesticQuestion,

    "types.AdmissionInternationalQuestion": types.AdmissionInternationalQuestion,
    "stream_types.AdmissionInternationalQuestion": stream_types.AdmissionInternationalQuestion,

    "types.ApplicationQuestion": types.ApplicationQuestion,
    "stream_types.ApplicationQuestion": stream_types.ApplicationQuestion,

    "types.CareerQuestion": types.CareerQuestion,
    "stream_types.CareerQuestion": stream_types.CareerQuestion,

    "types.ClassifiedQuestion": types.ClassifiedQuestion,
    "stream_types.ClassifiedQuestion": stream_types.ClassifiedQuestion,

    "types.ContactQuestion": types.ContactQuestion,
    "stream_types.ContactQuestion": stream_types.ContactQuestion,

    "types.FinancialQuestion": types.FinancialQuestion,
    "stream_types.FinancialQuestion": stream_types.FinancialQuestion,

    "types.LocationQuestion": types.LocationQuestion,
    "stream_types.LocationQuestion": stream_types.LocationQuestion,

    "types.OtherQuestion": types.OtherQuestion,
    "stream_types.OtherQuestion": stream_types.OtherQuestion,

    "types.RankingQuestion": types.RankingQuestion,
    "stream_types.RankingQuestion": stream_types.RankingQuestion,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.UniQuery": types.UniQuery,
    "stream_types.UniQuery": stream_types.UniQuery,


    "types.AdmissionDomesticSubgroup": types.AdmissionDomesticSubgroup,

    "types.AdmissionInternationalSubgroup": types.AdmissionInternationalSubgroup,

    "types.ApplicationSubgroup": types.ApplicationSubgroup,

    "types.CareerSubgroup": types.CareerSubgroup,

    "types.ContactSubgroup": types.ContactSubgroup,

    "types.FinancialSubgroup": types.FinancialSubgroup,

    "types.LocationSubgroup": types.LocationSubgroup,

}